aws_access_key = "your_aws_access_key"
aws_secret_key = "your_aws_secret_key"
aws_region = "your_aws_region"
db_name = "your_aws_db_name"
db_username = "your_aws_db_username"
db_password = "your_aws_db_password"
db_identifier = "your_aws_db_identifier"